<?php

namespace Istruzioni\Entity\Repository;

/**
 * IstruzioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IstruzioneRepository extends \Doctrine\ORM\EntityRepository
{
}
